apiVersion: v1
kind: Service
metadata:
  name: data-updater
  labels:
    prometheus-scrape: "true"
spec:
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP
  selector:
    app: data-updater