apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: answer-generator-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: answer-generator-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75