apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes 1;

    events {
      worker_connections 1024;
    }

    http {
      upstream qa-api {
        server qa-api:7777;
      }

      upstream qa-ui {
        server qa-ui:3000;
      }

      upstream data-updater {
        server data-updater:7777;
      }

      server {
        listen 7800;

        location /api/ {
          proxy_pass http://qa-api/;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $host;
        }

        location /ws/ {
          proxy_pass http://data-updater/;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $host;
        }

        location / {
          proxy_pass http://qa-ui;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $host;
        }
      }
    }
